---
- hosts: "{{ hosts }}"

  become: true
  tasks:

    - name: install sysupdate
      copy:
        dest: /usr/local/bin/sysupdate
        src: "{{ sup }}"
        mode: 0700
        owner: root
        group: root

    - name: install remove old kernels
      copy:
        dest: /usr/local/bin/remove_old_kernels
        src: "{{ rok }}"
        mode: 0700
        owner: root
        group: root

    - name: install install docker-compose
      copy:
        dest: /usr/local/bin/install_docker-compose
        src: "{{ doc }}"
        mode: 0700
        owner: root
        group: root

    - name: Modify file for ntp
      lineinfile:
        path: /etc/systemd/timesyncd.conf
        regexp: '^#NTP=$'
        insertafter: "[Time]"
        line: NTP=192.168.66.30
        owner: root
        group: root
        mode: '0644'

    - name: "Set up language, keyboard"
      copy:
        dest: "/etc/default/locale"
        content: |
          LANG=en_US.UTF-8
          LC_TIME=C.UTF-8
