---
- hosts: "adg1.acat.se"

  become: true
  tasks:

    - name: install sysupdate
      copy:
#        src: "{{ sysupdate }}"
        src: /opt/files/sysupdate
        dest: /usr/local/bin/sysupdate
        mode: 0700
        owner: root
        group: root
