---
- host: "{{ hosts }}"

  become: yes
  tasks:

    - name: install sysupdate
      copy:
        src: "{{ sysupdate }}"
        dst: "/usr/local/bin/sysupdate"
        mode: 0700
        owner: root
        group: root

