---
- hosts: "{{ ubuntu }}"

  become: true
  tasks:

    - name: install sysupdate
      copy:
        dest: /usr/local/bin/sysupdate
        src: "{{ sup }}"
        mode: 0700
        owner: root
        group: root

    - name: install remove old kernels
      copy:
        dest: /usr/local/bin/remove_old_kernels
        src: "{{ rok }}"
        mode: 0700
        owner: root
        group: root

    - name: install install docker-compose
      copy:
        dest: /usr/local/bin/install_docker-compose
        src: "{{ doc }}"
        mode: 0700
        owner: root
        group: root
