---
- hosts: "{{ hosts }}"

  become: true
  tasks:

    - name: install .bashrc
      copy:
        src: "{{ brc }}"
        dest: "~/.bashrc"
        mode: '0644'

    - name: create folder for .bash
      file:
        path: "~/.bash"
        state: directory
        mode: '0755'

    - name: copy file 1 to .bash
      copy:
        src: "{{ ali }}"
        dest: "~/.bash/bash_aliases"
        mode: "0644"

    - name: copy file 2 to .bash
      copy:
        src: "{{ fun }}"
        dest: "~/.bash/bash_functions"
        mode: "0644"

    - name: copy file 3 to .bash
      copy:
        src: "{{ pro }}"
        dest: "~/.bash/bash_prompt"
        mode: "0644"
