---
- hosts: "{{ hosts }}"

  become: true
  tasks:

    - name: install .bashrc
      copy:
        src: "{{ brc }}"
        dest: "~/.bashrc"
        mode: '0644'

    - name: create folder for .bash
      file:
        path: "~/.bash"
        state: directory
        mode: '0755'
        