---
- hosts: "{{ hosts }}"

  become: yes
  tasks:

    - name: install-sysupdate
      copy:
        src: "{{ sysupdate }}"
        dest: "/usr/local/bin/sysupdate"
        mode: "0700"
        owner: "root"
        group: "root"
