---
- hosts: "adg1.acat.se"

  become: true
  tasks:

    - name: install sysupdate
      copy:
        dest: /usr/local/bin/sysupdate
        src: "{{ sysupdate }}"
        mode: 0700
        owner: root
        group: root
