---
- hosts: all

  tasks:

    - name: Get disk usage
      command: df -h
      register: disk_usage

    - name: Check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage

    - name: Send e-mail
      mail:
        host: 192.168.66.8
        port: 25
        subject: Ansible report
        body: '{{ inventory_hostname }} is running low on disk space. Currently {{ disk_free.results['item']['size_available'] }}MB available.'
        from: semaphore@sm0etv.se
        to: thomas@sm0etv.se

