---
- hosts: all

  become: true
  tasks:
    # Upgrade packages
    - name: update apt packages
      apt:
        upgrade: "safe"
        update_cache: true

    # Clean up
    - name: clean up stuff
      apt:
        autoremove: true
        clean: true
        autoclean: true

    # Check if reboot is required
    - name: Check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    # Send e-mail when reboot is required
    - name: Send e-mail
      mail:
        host: 192.168.66.8
        port: 25
        to: thomas@sm0etv.se
        from: semaphore@sm0etv.se
        subject: Ansible-report
        body: '{"content": "Reboot required on {{ inventory_hostname }}"}'
        headers:
          Content-type: application/json
        status_code: 204
      when: reboot_required_file.stat.exists
