---
- hosts: all

  become: true
  tasks:
    # Upgrade packages
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes

    # Clean up
    - name: clean up stuff
      apt:
        autoremove: yes
        clean: yes
        autoclean: yes

    # Check if reboot is required
    - name: Check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
